spring.application.name=RelayPay
spring.data.mongodb.uri=mongodb+srv://deepikabhati207_db_user:8SBlK331Zz6jKhRS@relaypay-cluster.lfmqdjg.mongodb.net/relaypay?appName=relaypay-cluster
server.port=9090

n